### PR TITLE
Support deskbar mode

### PR DESCRIPTION
**Pull request by hjudt**
Set small attribute for plugin and connect mode_changed signal instead
of the old orientation_changed signal.

### CODE REVIEW

**Comment by equeim** [comment]
Will it make it depend on newer version of libxfce4panel?

**Comment by hjudt** [comment]
It should work with >=xfce4-panel-4.11, the version where mode_changed has been introduced.

**Comment by hjudt** [comment]
bump?

**Comment by equeim** [comment]
Sorry, totally forgot about it.

**Pull request merged**
